"""Modular package exposing the REAP toolkit components."""
from .encoders import (
    DEFAULT_ENCODER,
    GridCodeBlockEncoder,
    GridEncoder,
    GridWithSeparationEncoder,
    MinimalGridEncoder,
)
from .grid_utils import (
    clamp,
    crop,
    deepcopy_grid,
    dims,
    enforce_invariants,
    eq_grid,
    fill_holes,
    flip,
    grid_to_template,
    make_grid,
    map_color,
    mirror_symmetry,
    overlay,
    pad,
    repeat_scale,
    tile_to_target,
    valid_grid,
)
from .types import Color, Coord, Example, Grid, Object, Template, TestItem, TrainPair

__all__ = [
    "DEFAULT_ENCODER",
    "GridCodeBlockEncoder",
    "GridEncoder",
    "GridWithSeparationEncoder",
    "MinimalGridEncoder",
    "clamp",
    "crop",
    "deepcopy_grid",
    "dims",
    "enforce_invariants",
    "eq_grid",
    "fill_holes",
    "flip",
    "grid_to_template",
    "make_grid",
    "map_color",
    "mirror_symmetry",
    "overlay",
    "pad",
    "repeat_scale",
    "tile_to_target",
    "valid_grid",
    "Color",
    "Coord",
    "Example",
    "Grid",
    "Object",
    "Template",
    "TestItem",
    "TrainPair",
]
